### ISSUE TITLE
2016 General Precinct Level Results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ky#2]
Parse the Excel files in the [Kentucky sources repo](https://github.com/openelections/openelections-sources-ky/tree/master/2016) and output either individual county-specific files or a single statewide precinct file.

The headers for those files:

`county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

You should include the following offices: President, U.S. Senate, U.S. House, State Senate and State House.

Ideally you'd write a script and include that script here.

**Comment by tamilyn** [comment]
I can do this in R.

**Comment by jonathankoren** [comment]
I've got a python script that does this, along with the CSV of results. Party isn't populated because that's not available in the XLS files. However I can't figure out how to submit this as a PR since I don't have commit access to the repo. :( 

In light of that, here's a gist: https://gist.github.com/jonathankoren/c89232586cdbe27c4505d5930846b334

**Comment by dwillis** [comment]
Hey @jonathankoren, thanks! Happy to accept this, and another way to do it is to fork the repository to your account, then commit your changes to that repo and create a pull request so that I can merge your changes into this repository.

**Comment by jonathankoren** [comment]
https://github.com/openelections/openelections-data-ky/pull/3

**Comment by dwillis** [comment]
I'm going to close this issue, but will add another to see if we can't match up candidate parties to the results file.
